apiVersion: apps/v1
kind: Deployment
metadata:
  name: porto-seguro-api
  labels:
    app: porto-seguro-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: porto-seguro-api
  template:
    metadata:
      labels:
        app: porto-seguro-api
    spec:
      containers:
      - name: porto-seguro-container
        image: jellewillekes/porto-seguro-api:latest
        ports:
        - containerPort: 8080
