name: CD

on:
  push:
    branches: [ "main", "feature/update-cd" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install conntrack
      - name: Install conntrack
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack

      # Install Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml