name: CD
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install conntrack
      - name: Install conntrack
        run: |
          sudo apt-get update -y
          sudo apt-get install -y conntrack

      # Install crictl
      - name: Install crictl
        run: |
          VERSION="v1.27.1" # Replace with the desired version
          curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
          sudo tar -C /usr/local/bin -xzf crictl-$VERSION-linux-amd64.tar.gz
          rm -f crictl-$VERSION-linux-amd64.tar.gz

      # Install Minikube
      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      # Start Minikube
      - name: Start Minikube
        run: |
          sudo minikube start --driver=none

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
