name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10 environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # Step 4: Start FastAPI application
      - name: Start FastAPI Server
        run: uvicorn serving.predict:app --host 0.0.0.0 --port 8080 &
        env:
          ENV: test  # Set environment variables if needed
        shell: bash

      # Step 5: Wait for the server to start
      - name: Wait for FastAPI Server
        run: |
          for i in {1..10}; do
            if curl --silent http://localhost:8080/health; then
              echo "FastAPI server is running!"
              exit 0
            fi
            echo "Waiting for FastAPI server..."
            sleep 5
          done
          echo "FastAPI server failed to start."
          exit 1

      # Step 6: Run unit tests
      - name: Run Unit Tests
        run: python -m unittest discover -s tests -p "*.py"

      # Step 7: Cleanup background jobs
      - name: Kill Background Processes
        if: always()
        run: kill $(jobs -p)
