name: CI Pipeline
on: [push, pull_request]  # Trigger CI on push and pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10 environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run Unit Tests
        run: python -m unittest discover -s tests -p "*.py"
