name: CI Pipeline
on: [push, pull_request]  # Run CI on push and pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.10 environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      # Step 4: Lint code using flake8
      - name: Lint Code
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Step 5: Run unit tests with coverage
      - name: Run Tests with Coverage
        run: |
          pip install coverage
          coverage run -m unittest discover -s tests -p "*.py"
          coverage report
          coverage xml

      # Step 6: Upload coverage report to GitHub Actions
      - name: Upload Coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml