name: CI Pipeline
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Start FastAPI Server
        run: |
          nohup uvicorn serving.predict:app --host 0.0.0.0 --port 8080 > server.log 2>&1 &
          echo $! > server_pid.txt
        env:
          ENV: test
        shell: bash

      - name: Wait for FastAPI Server
        run: |
          for i in {1..10}; do
            if curl --silent http://localhost:8080/health; then
              echo "FastAPI server is running!"
              exit 0
            fi
            echo "Waiting for FastAPI server..."
            sleep 5
          done
          echo "FastAPI server failed to start."
          exit 1
        shell: bash

      - name: Run Unit Tests
        run: python -m unittest discover -s tests -p "*.py"
        shell: bash

      - name: Kill FastAPI Server
        if: always()
        run: |
          kill $(cat server_pid.txt)
          rm server_pid.txt
        shell: bash
